##
##  ASTy -- Abstract Syntax Tree (AST) Data Structure
##  Copyright (c) 2014-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##
##  Permission is hereby granted, free of charge, to any person obtaining
##  a copy of this software and associated documentation files (the
##  "Software"), to deal in the Software without restriction, including
##  without limitation the rights to use, copy, modify, merge, publish,
##  distribute, sublicense, and/or sell copies of the Software, and to
##  permit persons to whom the Software is furnished to do so, subject to
##  the following conditions:
##
##  The above copyright notice and this permission notice shall be included
##  in all copies or substantial portions of the Software.
##
##  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
##  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
##  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
##  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
##  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
##  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
##  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

#   all-in-one development
dev
    nodemon --exec "npm start lint build test" --watch src --ext ts

#   static code analysis (linting)
lint
    tsc --build etc/tsc.json --noEmit && \
    oxlint --config etc/oxlint.jsonc src/*.ts && \
    eslint --config etc/eslint.mts src/*.ts

#   static code analysis (linting) [watching]
lint-watch
    nodemon --exec "npm start lint" --watch src --ext ts

#   code compilation/transpiling (building)
build
    VITE_BUILD_FORMATS=esm,cjs vite --config etc/vite.mts build --mode production
    VITE_BUILD_FORMATS=umd     vite --config etc/vite.mts build --mode production

#   code compilation/transpiling (building) [watching]
build-watch
    nodemon --exec "npm start build" --watch src --ext ts

#   run test suite and sample
test
    NODE_OPTIONS="--import=tsx" mocha tst/asty.spec.ts

#   cleanup (built artifacts)
clean
    shx rm -rf dst-stage1 dst-stage2 etc/tsc.tsbuildinfo

#   cleanup (bootstrap artifacts)
distclean: clean
    shx rm -rf node_modules

